Hw03 frequency analysis
pinguini/otus_hw pull request #3
Opened 2023-06-22 15:16 UTC by pinguini

2023-06-23 16:02 UTC, engineer-go commented on hw03_frequency_analysis/top.go
> +	return input
Интересное решение, а почему вы не использовали тот же regexp? Да и как многие делают после stings.fields, можно просто отдельные значения вроде - пропускать не записывая в финальный массив.

2023-06-23 16:02 UTC, engineer-go commented on hw03_frequency_analysis/top.go
> +	return input
Тут вроде как получается 6 вызовов со сложностью o(n)

2023-06-23 16:02 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +	}
вот это кажется черезчур усложнённо, попробуйте сначала создавать мапу частот, потом сделать слайс собственно слов, и отталкиваясь от мапы уже, осортировать сам слайс с помощью того же slice.Sort(). Должно упростить и укоротить решение.

2023-06-23 16:02 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +	}
ну и слайс strings проще уже будет обрезать под нужный вам размер.

2023-06-24 05:26 UTC, pinguini commented on hw03_frequency_analysis/top.go
> +	return input
мы регулярки по обучению не проходили))) потому и не использовал 
но исправлю на регулярку - собственно в комментарии я так и написал

2023-06-25 20:27 UTC, ityulkanov requested changes
Добавил парочку комментариев, но уже больше по стилю. Напишите, пожалуйста хотя бы один тест свой и приму.

2023-06-25 20:27 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +		keys = keys[0:10]
```suggestion
		keys = keys[:10]
```

2023-06-25 20:27 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +			keys = append(keys, wordText)
оригинально) Даже не думал о таком варианте, обычно прогоняют уже после)

2023-06-25 20:27 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +		return words[keys[i]] > words[keys[j]] || (words[keys[i]] == words[keys[j]] && strings.Compare(keys[j], keys[i]) > 0)
имхо, keys[i], keys[j] было бы правильнее вынести в переменную, сейчас падает читаемость

2023-06-26 05:43 UTC, ityulkanov approved these changes

2023-07-02 14:37 UTC, merged