Hw04 lru cache
pinguini/otus_hw pull request #4
Opened 2023-07-02 14:55 UTC by pinguini

hw04

2023-07-03 11:09 UTC, ityulkanov requested changes
Антон, добрый день. Оставил пару небольших комментариев, как поправите, приму

2023-07-03 11:09 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +		for k := range c.items {
Пока что работу принять не смогу, т.к. вот тут у нас не выполняется условие по o(1). 
Подсказка: вы можете записывать в interface{} любое значение.

2023-07-03 11:09 UTC, ityulkanov commented on hw04_lru_cache/list.go
> +	if l.head == li {
несмотря на то, что в ДЗ оговорено что удаляем мы не из пустого списка, всё же рекомендую проверять такую проверку (к примеру l.len == 0 -> panic), как признак хорошего тона, т.к. в случае если кто то после вас решит изменить данный контракт, Remove сломается там где не должен.

2023-07-03 14:44 UTC, pinguini commented on hw04_lru_cache/list.go
> +	if l.head == li {
тут ещё другой вопросик 
у нас может быть два списка 
и у нас нет проверки на то принадлежит ли элемент данному списку 
и мы можем следующее 

listA.pushForward (10)

2023-07-04 11:23 UTC, ityulkanov commented on hw04_lru_cache/list.go
> +	if l.head == li {
Не очень понимаю как у нас может быть 2 списка, если мы передаём указатель на один конкретный список

2023-07-04 11:31 UTC, ityulkanov commented on hw04_lru_cache/list.go
> +	if ok && val {
имхо, тогда правильнее !ok return делать, а всё остальное уже как было оставить

2023-07-04 11:42 UTC, ityulkanov approved these changes

2023-07-04 13:08 UTC, merged